## Recurrent Neural Networks - Supervised Learning II - MDS Computational Linguistics

### Goal of this tutorial
- Learn about embedding layer
- Introduce Recurrent Neural Networks (RNNs)
- Implement RNN for sentiment analysis
- Implement Long-Short Term Memories (LSTMs) for sentiment analysis
- Implement Gated Recurrent Units (GRUs) for sentiment analysis

### General
- This notebook was last tested on Python 3.6.9 and PyTorch 1.2.0
- This notebook uses torchtext to process datasets

We would like to acknowledge the following materials that helped as a reference in preparing this tutorial:
- https://github.com/UBC-NLP/dlnlp2019/blob/master/slides/RNN.pdf

### Getting Started

In [1]:
# required imports
import pandas as pd
import torchtext
from torchtext.data import Field, LabelField
from torchtext.data import TabularDataset
import torch
import torch.nn as nn

#### Embedding Layer

Embedding layer is the ubiquitous input layer of deep neural networks used in NLP.

The [``Embedding`` layer](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html#embedding) in Pytorch (that we used in the last week's tutorial on Word2vec) is a lookup table that is typically (in NLP) used to store word embeddings of a fixed vocabulary and word embedding size. Word embeddings can be retrieved from the lookup table by providing a list of word index as input to the layer. We need to know what the input and the output of this layer look like. Let's first look at a dummy example where we have two sentences ``x_1`` and ``x_2``. Let's assume we have the two sentences as:

In [2]:
x_1 = "He is very nice" # sentence 1
x_2 = "She is very kind" # sentence 2

Let's convert the two sentences into indexes (each word is replaced with its index in the vocabulary).
Let's assume our ``vocabulary size`` is set to 100. Remember, vocabulary size is a hyper-parameter.
Let's also store that ``vocabulary size`` in a variable ``VOCAB_SIZE`` now as we will need to pass it to the ``Embedding`` layer later.

In [3]:
x_1 = [1, 25, 40, 5]
x_2 = [4, 25, 40, 99]
VOCAB_SIZE = 100

#### Max sequence length

One last thing we need to think about is the ``length of each sequence``. The two examples above are nicely set to equal length = 4. This does not need to be the case, as we can have sequences of varying lengths. We will be passing a batch of sentences to Pytorch and the max sequence length will be set to the length of the longest sentence (after tokenization) in that batch. The rest of sentences (shorter ones) will be padded with zeros. Now, do we need to explicitly provide the max sequence length to Pytorch? And how do we know the max seq length for each batch, if different batches have sequences of varying lengths and each batch is set to the max sent in that batch? Well, rest assured, we don't really need to worry about that. Pytorch will assign a max seq length for each batch. We will be able to inspect the max seq length for a given batch using output of the ``Embedding`` layer. (We will see that soon).

#### Size of word vector

The ``Embedding`` layer will give us a vector for each word in the vocabulary.
Now, we will need to tell it what size we want for that vector. Popular values for a vector size are usually between 100-300 for many tasks (e.g., sentiment analysis). Let's set it to 200 dimensions. (You are encouraged to play with this value as practice). All words in the vocabulary will have the same embedding size. Let's put that hyper-parameter in a variable ``WORD_VEC_SIZE``:

In [4]:
WORD_VEC_SIZE= 300 # size of word embedding

We are now ready to call the ``Embedding`` class to construct an embeddings tensor:

In [5]:
# Constructing an embedding Layer:
embedding = nn.Embedding(VOCAB_SIZE, WORD_VEC_SIZE)
print("size of the embedding lookup table = ", embedding.weight.data.size())

# let's create a sample input (word indices) to the embedding layer 
sample_input = torch.LongTensor([ x_1, x_2 ])
print("input (word indices) tensor = \n", sample_input)
print("input (word indices) shape = ", sample_input.size())

size of the embedding lookup table =  torch.Size([100, 300])
input (word indices) tensor = 
 tensor([[ 1, 25, 40,  5],
        [ 4, 25, 40, 99]])
input (word indices) shape =  torch.Size([2, 4])


Let's pass the input to the embedding layer and print the word embeddings:

In [6]:
# let's pass the input to the embedding layer
word_embeddings = embedding(sample_input)
print("word embeddings tensor = \n", word_embeddings)

word embeddings tensor = 
 tensor([[[-2.2900,  1.1938, -0.3543,  ...,  0.0531,  0.6758, -0.0898],
         [-0.8958,  1.7066, -0.8030,  ...,  0.7520, -1.8912, -0.1231],
         [ 1.9786,  1.1196,  0.2450,  ...,  1.4984, -1.0921, -0.3142],
         [-1.2194,  0.2972,  0.4722,  ..., -0.4976, -0.7058,  0.2130]],

        [[ 1.1034, -1.2716, -0.4433,  ..., -0.6279,  0.6257, -1.0109],
         [-0.8958,  1.7066, -0.8030,  ...,  0.7520, -1.8912, -0.1231],
         [ 1.9786,  1.1196,  0.2450,  ...,  1.4984, -1.0921, -0.3142],
         [-0.1536, -0.1753, -1.9731,  ..., -0.1736,  0.5713,  1.1744]]],
       grad_fn=<EmbeddingBackward>)


Let's print the shape of this tensor:

In [7]:
print("word embeddings shape = ", word_embeddings.size())

word embeddings shape =  torch.Size([2, 4, 300])


Each dimension can be interpreted as:
- **First dimension:** (**2**,4,300): We have ``2 examples`` (that is, our ``x_1`` and ``x_2``). (Note: We will be passing a whole batch to the ``Embedding`` class and so this first dimension will be equal to the ``batch size``.
- **Second dimension:** (2,**4**,300): For each of the two examples, we have a ``max sequence length`` = 4 (x_1 and x_2 each had 4 indexes).
- **Third dimension:** (2,4,**300**): The ``word vector dimension`` is set to 300.

### Max sequence length: Another note

Recall from above we mentioned Pytorch automatically infers the max sequence length for each batch. 
For the example above (as you can see from the second dimension returned by ``word_embeddings.size()``, Pytorch 
inferred the max seq length for this batch of two sentences is 4.

Let's just adjust the second example, **adding two more words** (the string "and kind"). Note, both our ``VOCAB_SIZE`` and ``WORD_VEC_SIZE`` stay the same as before. We assign the word "and" an index of "7" and the word "considerate" an index of "60". Note that we have to pad the first example ``x_1`` with zeros (we will explicitly set the padding index to zero later when we define the embedding layer) in the end. (Try removing the zero padding. What do you observe when you run your code with the ``Embedding`` class? Hint: You will get an error.):

In [8]:
x_1 = "He is very nice"
x_2 = "She is very kind and considerate"
x_1 = [1, 25, 40, 5, 0, 0]
x_2 = [4, 25, 40, 99, 7, 60]

Now, let's create a new ``embedding`` layer by creating a new instance of the ``Embedding`` class:

In [9]:
# constructing an embedding layer:
padded_embedding = nn.Embedding(VOCAB_SIZE, WORD_VEC_SIZE, padding_idx=0)
print("size of the embedding lookup table = ", padded_embedding.weight.data.size())

size of the embedding lookup table =  torch.Size([100, 300])


Note that **padded_embedding** embedding layer specifies the padding index (corresponds to an embedding initialized to all zeros). In this example, the zeroth index is dedicated for storing padding embedding (vector initialized to all zeros).

Let's create sample input and pass it to the embedding layer.

In [10]:
# let's create a sample input
sample_input = torch.LongTensor([ x_1, x_2 ])
print("input (word indices) tensor = \n", sample_input)
print("input (word indices) shape = ", sample_input.size())

# let's retrieve the word embeddings by passing the sample input to the layer
word_embeddings = padded_embedding(sample_input)
print(word_embeddings)

input (word indices) tensor = 
 tensor([[ 1, 25, 40,  5,  0,  0],
        [ 4, 25, 40, 99,  7, 60]])
input (word indices) shape =  torch.Size([2, 6])
tensor([[[ 0.5945, -0.3828,  0.3309,  ..., -0.1188, -0.1239, -1.4457],
         [-0.0399, -0.5573,  1.3314,  ...,  1.1349, -0.5850,  0.5166],
         [ 0.2546, -0.7137, -0.4549,  ...,  0.5637,  1.1389,  0.6419],
         [-1.1444,  0.7108,  0.0503,  ...,  0.8641,  1.0224, -0.0170],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.2023, -0.4251, -1.3698,  ...,  0.4891,  0.7745,  0.6198],
         [-0.0399, -0.5573,  1.3314,  ...,  1.1349, -0.5850,  0.5166],
         [ 0.2546, -0.7137, -0.4549,  ...,  0.5637,  1.1389,  0.6419],
         [-1.8886, -0.8846, -0.3505,  ...,  1.1404, -0.2377, -1.4031],
         [ 0.6424,  1.4108,  0.1285,  ..., -0.4306,  0.6597, -1.1780],
         [-1.2783,  0.3748, -0.2331,  ..., -0.3626, -1.5141,  0.561

If we inspect the shape of the new tensor ``word_embeddings``, we will see the second dimension now changed to 6, to match the max sequence length:

In [11]:
print(word_embeddings.size())

torch.Size([2, 6, 300])


### How does Pytorch initialize word vector dimensions/weights?

Note that Pytorch initializes the word vectors with initialized from a **normal distribution** $ \mathcal{N}(0, 1) $. The word embedding weights are by default learnable parameters in Pytorch and so they will be adjusted during training. (Note: These weights can be initialized from an external word embedding tool such as [Word2vec](https://code.google.com/archive/p/word2vec/), [Fasttext](https://fasttext.cc/), or [Glove](https://nlp.stanford.edu/projects/glove/). Also, the weights can be frozen (by setting ``embedding.weigh.required_grad`` flag to False), which is a reasonable option when initialized from an external tool. You can choose to keep learning them within the model with your training data). Below we show the ones initialized from a normal distribution by Pytorch.

In [12]:
embedding.weight

Parameter containing:
tensor([[ 0.0660,  0.7667,  1.1340,  ..., -0.4354,  0.3147, -1.2718],
        [-2.2900,  1.1938, -0.3543,  ...,  0.0531,  0.6758, -0.0898],
        [ 1.2738, -0.5127,  0.3308,  ..., -0.2098,  0.4477, -1.0887],
        ...,
        [ 0.8932,  1.4609,  0.5909,  ..., -1.4103,  1.8776,  0.8554],
        [-0.3136,  0.8598,  0.8790,  ..., -0.2526, -0.5394, -0.1592],
        [-0.1536, -0.1753, -1.9731,  ..., -0.1736,  0.5713,  1.1744]],
       requires_grad=True)

More information about the ``Embedding`` class can be found [here](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html) ([source code](https://pytorch.org/docs/stable/_modules/torch/nn/modules/sparse.html#Embedding)).

## Recurrent Neural Networks
Recurrent Neural Networks (RNNs) are used to model sequences of arbitrary length (e.g., sequence of words in a sentence, sequence of sentences in a document, sequence of frames in a video). RNNs typically use their internal state (memory) to process sequence of inputs. At each time-step, RNNs output a prediction and hidden state, feeding its previous hidden state into each next step. RNNs are applied in a wide range of NLP applications:
- language modeling, where RNN can condition on **all** previous words in the corpus unlike n-gram language model
- text classification, where the states act as features (we will see sentiment analysis in this tutorial)
- machine translation, where a RNN is used to process a sentence in source language and another RNN is used to decode the sentence in target language (we will see this in the "Machine Translation" course)
- sequence labeling, where the states in RNN are used to predict a category for each item in the sequence 

Recommended reading for understanding the theory of RNNs: https://github.com/UBC-NLP/dlnlp2019/blob/master/slides/RNN.pdf 


### Grabbing few tweets using torchtext

Let us follow **torchtext** tutorial (seen in Week1) to read few tweets from the [sentiment analysis dataset](http://alt.qcri.org/semeval2016/task4/) used in the previous tutorial on feedforward neural networks. The preprocessed (tokenization, removing URLs, mentions, hashtags and so on) tweets are placed under ``data/sentiment-twitter-2016-task4`` folder in three files as ``train.tsv``, ``dev.tsv`` and ``test.tsv``.  

Let us view few tweets from ``train.tsv`` using pandas.

In [13]:
import pandas as pd
df = pd.read_csv("./data/sentiment-twitter-2016-task4/train.tsv", sep = '\t', header=None, names=['tweet','label']) # the separator of tsv file is `\t`
df.head()

tweet  label
0  dear <<<MENTION>>> the newooffice for mac is g...      2
1  <<<MENTION>>> how about you make a system that...      2
2  i may be ignorant on this issue but should we ...      2
3  thanks to <<<MENTION>>> i just may be switchin...      2
4  if i make a game as a <<<HASHTAG>>> universal ...      0

**We import the relevant packages, define the tokenizer and TorchText's fields.**

In [14]:
# import related packages
import torchtext
from torchtext.data import Field, LabelField
from torchtext.data import TabularDataset

# define the white space tokenizer to get tokens
def tokenize_en(tweet):
    """
    Tokenizes English tweet from a string into a list of strings (tokens)
    """
    return tweet.strip().split()

# define the TorchText's fields
TEXT = Field(sequential=True, tokenize=tokenize_en, lower=True)
LABEL = Field(sequential=False, unk_token = None)

**To use the different splits (training, development and testing), we use `TabularDataset` class to load datasets.**

In [15]:
train, val, test = TabularDataset.splits(
    path="./data/sentiment-twitter-2016-task4/", # the root directory where the data lies
    train='train.tsv', validation="dev.tsv", test="test.tsv", # file names
    format='tsv',
    skip_header=False, # if your tsv file has a header, make sure to pass this to ensure it doesn't get proceesed as data!
    fields=[('tweet', TEXT), ('label', LABEL)])

**Build our vocabulary to map words to integers.**

In [16]:
TEXT.build_vocab(train, min_freq=3) # builds vocabulary based on all the words that occur at least twice in the training set
LABEL.build_vocab(train)

**Initialize the iterators for the train, validation, and test data. Note that we set ``sort`` as `False` so as to not sort examples based on similar lengths which minimizes padding.**

In [17]:
from torchtext.data import Iterator, BucketIterator

train_iter, val_iter, test_iter = BucketIterator.splits(
 (train, val, test), # we pass in the datasets we want the iterator to draw data from
 batch_sizes=(4,64,64),
 sort_key=lambda x: len(x.tweet), 
 sort=False,
# A key to use for sorting examples in order to batch together examples with similar lengths and minimize padding. 
 sort_within_batch=False
)

**Create a batch of four examples and print them**

In [18]:
# create a single batch and terminate the loop
for batch in train_iter:
    tweets = batch.tweet
    labels = batch.label
    break  #we use first batch as an example.

# print the four examples with padding and corresponding label
print("processed tweets: ")
for j in range(tweets.shape[1]): # sample loop
    tokens = []
    for i in range(tweets.shape[0]): # token loop
        tokens.append(TEXT.vocab.itos[tweets[i,j]])
    print(j," sample:",tokens," label:", labels[j].item())

processed tweets: 
0  sample: ['google', 'results', 'are', '<unk>', 'so', 'i', 'may', 'well', 'only', 'show', 'up', 'so', 'high', 'if', "you're", 'in', 'the', 'uk', '<pad>', '<pad>', '<pad>', '<pad>']  label: 1
1  sample: ['pretty', '<unk>', 'by', 'bentley', 'over', 'charles', 'she', 'has', '<<<digit>>>', '<unk>', '<<<digit>>>', 'sun', '<<<digit>>>', '<unk>', 'with', 'the', '<unk>', 'for', 'her', 'first', '<unk>', '<pad>']  label: 1
2  sample: ['<<<hashtag>>>', 'car', 'news', 'lexus', 'may', 'reveal', 'a', 'new', '<unk>', 'fuel', '<unk>', 'car', 'lexus', 'has', 'plans', 'to', 'reveal', 'the', 'new', '<unk>', '<<<url>>>', '<<<hashtag>>>']  label: 0
3  sample: ['seen', 'girls', 'crying', 'for', 'beyonce', 'crazy', 'but', 'when', 'march', 'madness', 'is', 'played', 'i', 'might', 'do', 'the', 'same', 'tomorrow', '<pad>', '<pad>', '<pad>', '<pad>']  label: 0


**Now we set ``sort`` as `True` so as to sort examples based on similar lengths which minimizes padding.**

**Let us initialize the new iterators for the train, validation, and test data.**

In [19]:
train_iter, val_iter, test_iter = BucketIterator.splits(
 (train, val, test), # we pass in the datasets we want the iterator to draw data from
 batch_sizes=(4,64,64),
 sort_key=lambda x: len(x.tweet), 
 sort=True,
# A key to use for sorting examples in order to batch together examples with similar lengths and minimize padding. 
 sort_within_batch=True
)

**Let us pick up 4 tweets from the training set and convert them to tensors.**

**Create a batch of four examples and print them**

In [20]:
# create a single batch and terminate the loop
for batch in train_iter:
    tweets = batch.tweet
    labels = batch.label
    break  #we use first batch as an example.

# print the four examples with padding and corresponding label
print("processed tweets: ")
for j in range(tweets.shape[1]): # sample loop
    tokens = []
    for i in range(tweets.shape[0]): # token loop
        tokens.append(TEXT.vocab.itos[tweets[i,j]])
    print(j," sample:",tokens," label:", labels[j].item())

processed tweets: 
0  sample: ['ihop', 'is', 'the', 'move', 'tomorrow']  label: 0
1  sample: ['<<<mention>>>', 'make', 'david', 'beckham', 'tomorrow']  label: 1
2  sample: ['bringing', 'the', 'bentley', 'out', 'tomorrow']  label: 0
3  sample: ['new', '<unk>', 'with', 'bentley', 'tomorrow']  label: 0


### Creating a single hidden layer RNN

PyTorch has ``torch.nn.RNN`` module that implements the vanilla (Elman) RNN with *tanh* or *ReLU* non-linearity. The documentation for this module is [here](https://pytorch.org/docs/stable/generated/torch.nn.RNN.html?highlight=nn%20rnn#torch.nn.RNN). Let us use the sample batch of five examples created before to understand this module.

In this tutorial, we will represent the input tweet using a sequence of word embeddings (for each word present in the tweet). We will use ``torch.nn.Embedding`` layer to store word vectors corresponding to words in the vocabulary.

Before implementing the embedding module for our usecase, let us compute the size of the word vocabulary.

In [21]:
# print the size of the word vocabulary
VOCAB_SIZE = len(TEXT.vocab.stoi)
print(VOCAB_SIZE)

3340


We have 3385 unique words in the vocabulary.

Let us implement the embedding module (whose underlying weight matrix shape is (``vocabulary size`` $\times$ ``word embedding size``) for our usecase:

In [22]:
# set the word embedding size
WORD_VEC_SIZE = 300

# an Embedding module containing 300 dimensional tensor for each word in the vocabulary
# Note, the parameters to Embedding class below are:
# num_embeddings (int): size of the dictionary of embeddings
# embedding_dim (int): the size of each embedding vector
# For more details on Embedding class, see: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/sparse.py
embedding = nn.Embedding(VOCAB_SIZE, WORD_VEC_SIZE, sparse=True)
print("lookup table shape = ", embedding.weight.size())

lookup table shape =  torch.Size([3340, 300])


Let us now feed the tensors of our sample batch to the embedding module and extract the sequence of word embeddings for each tweet.

In [23]:
# print tensor containing word ids for our batch
print("*"*50, "\n Word ids for the first batch (recall, it has 4 sentences, each column representing a sentence): \n", tweets.data, "\n","*"*50,)

# feed the "word ids" tensor to the embedding module
tweet_input_embeddings = embedding(tweets)

# print the dimensions of the tweet_embeddings
print("*"*50, "\n Tweet input word embeddings size: ", tweet_input_embeddings.size(), "\n","*"*50,) 
# first dimension - sequence length: number of words per example (same across the whole batch, after padding) --> max_seq = 22
# second dimension -  batch size / number of examples in the batch --> 4
# third dimension - number of dimensions in the word vector

************************************************** 
 Word ids for the first batch (recall, it has 4 sentences, each column representing a sentence): 
 tensor([[ 191,    4, 1273,   49],
        [  14,   82,    2,    0],
        [   2,   73,  215,   18],
        [ 598,  145,   48,  215],
        [  21,   21,   21,   21]]) 
 **************************************************
************************************************** 
 Tweet input word embeddings size:  torch.Size([5, 4, 300]) 
 **************************************************


Let's actually view the actual word embeddings tensor for this batch:

In [24]:
print("*"*50, "\n Embeddings for the first batch: \n", tweet_input_embeddings, "\n","*"*50,) 

************************************************** 
 Embeddings for the first batch: 
 tensor([[[-2.0943e+00,  7.8867e-02, -8.1978e-01,  ...,  1.0347e-01,
           3.7766e-01,  4.1062e-01],
         [-7.1849e-01, -1.2141e+00,  1.9462e-01,  ...,  9.2544e-01,
          -9.7137e-01,  3.6893e-01],
         [-2.7343e-01,  3.4107e-01,  8.6145e-01,  ...,  5.8453e-01,
          -9.1968e-01,  2.9088e-01],
         [ 1.8260e-01,  3.3123e-01,  8.9203e-01,  ...,  3.5806e-01,
           1.8268e+00,  2.5625e-01]],

        [[ 1.4287e-01,  1.6546e+00,  1.8814e+00,  ...,  1.3174e+00,
          -4.5729e-01,  1.2268e+00],
         [-7.8575e-01, -8.9163e-01, -7.8823e-02,  ..., -2.8240e-01,
          -5.4606e-01, -1.1003e-01],
         [-1.0293e+00, -3.4893e-01, -8.6278e-01,  ...,  1.1109e+00,
          -2.4980e-01,  1.3902e+00],
         [-4.6459e-01, -2.9787e+00,  4.5081e-01,  ..., -1.2796e+00,
          -2.8013e-01, -3.6385e-01]],

        [[-1.0293e+00, -3.4893e-01, -8.6278e-01,  ...,  1.1109e+00,
 

What we are seeing is the actual word vectors representing each of the 4 sentences (i.e., whole batch).
This is dimension 2 in ``tweet_input_embeddings``. 

In [25]:
tweet_input_embeddings.size()[1]

4

As mentioned, ``max_seq length`` for this batch is ``5``, which is dimension 1 (indexed as 0 in Pytorch, similar to Python) 
in ``tweet_input_embeddings``: 

In [26]:
tweet_input_embeddings.size()[0]

5

Now, dimension 3 in ``tweet_input_embeddings`` (indexed as 2) is the size of the word vectors:

In [27]:
tweet_input_embeddings.size()[2]

300

Let's look at the vector for the ``first word`` in the ``first sentence`` in the batch:

In [28]:
tweet_input_embeddings[:1, :1, :].shape

torch.Size([1, 1, 300])

In [29]:
tweet_input_embeddings[:1, :1, :]

tensor([[[-2.0943e+00,  7.8867e-02, -8.1978e-01,  7.1793e-01,  5.8440e-01,
           4.3431e-01, -6.1536e-01, -3.8800e-01, -9.9230e-02,  4.1799e-01,
          -5.6369e-02,  1.0250e-01,  2.7171e+00, -2.4577e-01,  1.0922e+00,
          -9.8211e-01,  7.2380e-01, -1.1021e+00,  5.0208e-01,  1.5855e+00,
          -4.3991e-01,  2.4696e-01, -1.3487e+00, -6.5002e-01,  1.5784e+00,
          -1.0210e-01, -3.4975e-01,  8.2976e-01, -1.6821e+00, -7.6709e-01,
           4.2581e-01, -8.0796e-01,  3.2808e-01,  2.4369e+00, -1.6130e+00,
          -5.6864e-01, -4.3710e-01,  1.4939e+00, -2.4566e-01,  4.5666e-01,
           1.2130e+00,  2.7950e-01,  8.1096e-01, -5.6002e-01,  1.5450e+00,
           4.4951e-01,  7.3361e-01, -9.8819e-01, -4.1536e-01,  3.1770e-01,
           1.1518e+00, -3.0327e-01,  1.6906e+00,  1.4499e+00, -1.2964e+00,
          -9.0572e-01, -7.4603e-01,  6.6683e-02, -1.6290e+00,  1.1984e-03,
           4.2511e-01,  1.9490e-01,  2.8708e-01, -1.0026e+00, -2.2926e-01,
          -1.1190e+00,  5

Let's look at the ``first 5 dimensions`` of that same ``first word`` of the ``first sentence``:

In [30]:
tweet_input_embeddings[:1, :1, :5]

tensor([[[-2.0943,  0.0789, -0.8198,  0.7179,  0.5844]]],
       grad_fn=<SliceBackward>)

The following shows you the ``first 5 dimensions`` of the ``first word`` from ``each of the 4 sentences``

In [31]:
tweet_input_embeddings[:1, :, :5]

tensor([[[-2.0943,  0.0789, -0.8198,  0.7179,  0.5844],
         [-0.7185, -1.2141,  0.1946,  0.4177, -0.4803],
         [-0.2734,  0.3411,  0.8615, -1.0964, -0.2927],
         [ 0.1826,  0.3312,  0.8920,  0.7347, -0.1152]]],
       grad_fn=<SliceBackward>)

The following shows you the ``last 7 dimensions`` of the ``last word`` from ``the last sentence``. Enjoy!

In [32]:
tweet_input_embeddings[-1:, -1:, -7:]

tensor([[[0.9582, 0.6254, 0.5656, 0.6983, 1.2678, 0.1128, 1.3684]]],
       grad_fn=<SliceBackward>)

We will be passing the sequence of word embeddings for each sentence in the batch as input to the RNN. But let's now define an RNN module first:

In [33]:
"""
define the RNN module
"""
# first input - number of dimensions for word vectors for a vector x (300, size of the word embedding)
# second input - number of nodes in hidden state h_t (50, size of the hidden layer)
# third input - number of recurrent layers (we set it to 1)
rnn = nn.RNN(input_size=300, hidden_size=50, num_layers=1) # input_size, hidden_size, num_layers
print(rnn)

RNN(300, 50)


We will now pass the ``tweet_input_embeddings`` (representations of words in our batch) to RNN. Before we do, we need to know RNN also *optionally* takes a parameter for the ``initial hidden state h0`` (that is, the hidden state we will input to the model before the forward propagation starts. If this vector is not explicitly specified, Pytorch will just initialize h0 to a tensor of zeros.)

Let's construct an ``initial hidden state h0``. Note the shape of its tensor, and what each of the 3 parameters it takes mean.

In [34]:
"""
hidden layer at time-step 0 (h_0)
"""
# first dimension - number of RNN layers (1)
# second dimension - number of examples/sentences in a batch
# third dimension - number of nodes in hidden layer (50, size of the hidden layer, that we specified as hidden_size in RNN construction)
h0 = torch.randn(1, 4, 50)
print("The shape as as expected: ", h0.shape)

The shape as as expected:  torch.Size([1, 4, 50])


Let us feed both the hidden representation constructed above and tweet embeddings to our RNN model.
We will get back two objects ``output`` and ``hn`` that we will need to understand.

In [35]:
"""
forward propagation over the RNN model
"""
output, hn = rnn(tweet_input_embeddings, h0) # h0 is optional input, defaults to tensor of 0's of apprpriate size (num_layers, batch, hidden_size) when not provided

But what is ``output``? Well, let's inspect its shape first:

In [36]:
# output = seq_len, batch, hidden_size (output features from last layer of RNN)
print("output size: ", output.size())

output size:  torch.Size([5, 4, 50])


Here's what we need to know about ``output``:
- The first dimension in the ``output`` tensor is the ``max_seq length`` (5). 
- The second dimension is ``batch_size`` (the number of examples/sentences in our batch = 4).
- The third dimension is the ``size of nodes/units`` in our hidden layer (=50). 

What is the shape of hn (tensor containing the hidden state for t=max_seq_length) ?

In [37]:
# h_n = num_layers, batch, hidden_size (hidden state for t=seq_len or hidden state at last timestep)
print("last hidden state size: ", hn.size())

last hidden state size:  torch.Size([1, 4, 50])


Here's what we need to know about ``hn``:
- ``hn`` is a tensor of shape (num_layers, batch_size, hidden_size / number of hidden layer nodes) containing the hidden state for the last ``time step`` 
(``t = max_seq_length``).

You can take the output representation for a tweet after processing the last token (t=seq_len or last timestep) and call the resulting representation as the tweet representation that **"summarizes" the information present** in the tweet. This tweet representation can further be used for a useful task like tweet classification (we will try out sentiment analysis later in this tutorial) by adding a classification module on top of the tweet representation.

Let us compute the final tweet representation:

In [38]:
tweet_output_embeddings = output[-1,:,:] # -1 fetches the embeddings from the last timestep
print("tweet output embeddings size: ", tweet_output_embeddings.size())
# first dimension - number of tweets in the batch (4)
# second dimension - number of features in hidden state h_t (50, size of the hidden layer)

tweet output embeddings size:  torch.Size([4, 50])


## Multilayered RNN

For some applications, we may need more than one hidden layer for RNN to model the information flow. Adding more layers requires fews changes.

Firstly, we change the ``num_layers`` argument to reflect the number of layers we want during the RNN module definition (we will define two hidden layers).

In [39]:
"""
define the RNN module
"""
# first input - number of dimesnions for word vectors for a vector x (300, size of the word embedding)
# second input - number of nodes in hidden layer (50, size of the hidden layer)
# third input - number of recurrent layers (we set it to 2)
rnn = nn.RNN(input_size=300, hidden_size=50, num_layers=2) # input_size, hidden_size, num_layers

Similar to single layered RNN, Multilayered RNN module takes two inputs: the ``initial hidden state h0`` for each element in the batch (at ``time step t=0``) and the ``input features`` (``tweet_input_embeddings`` in our case).

Let us construct the new initial hidden state for a 2 layered RNN.

In [40]:
"""
hidden layer at time-step 0 (h_0)
"""
# first dimension - number of RNN layers (2)
# second dimension - number of examples/sentences in a batch (4)
# third dimension - number of nodes in hidden layer (50, size of the hidden layer)
h0 = torch.randn(2, 4, 50)
print("The shape as as expected: ", h0.shape)

The shape as as expected:  torch.Size([2, 4, 50])


Let us feed both the hidden representation constructed above and tweet embeddings to our RNN model.

In [41]:
"""
forward propagation over the RNN model
"""
print(tweet_input_embeddings.shape)
output, hn = rnn(tweet_input_embeddings, h0) # h0 is optional input, defaults to tensor of 0's when not provided

torch.Size([5, 4, 300])


``output`` tensor contains the output features $h_t$ from the last layer of the RNN

In [42]:
# output = seq_len, batch, hidden_size (output features from last layer of RNN)
print("output size: ", output.size())

output size:  torch.Size([5, 4, 50])


``hn`` is a tensor of shape (num_layers, batch_size, hidden_size / number of nodes in a hidden layer) containing the hidden state for last time step ``t = max_seq_len`` for the ``2 layered RNN``.

In [43]:
# h_n = num_layers, batch, hidden_size (hidden state for t=seq_len or hidden state at last timestep)
print("last hidden state size: ", hn.size())

last hidden state size:  torch.Size([2, 4, 50])


#### Building tweet representation

Actually, `output` is tensor containing the output features (h_t) from the last layer of the RNN, for each t. Namely, `output` returns all the hidden states of all time steps from the last layer of the RNN. Hence, the last element of `output` is `h_n`. 
Let us print them out:

In [44]:
print("last element of output:\n", output[-1])

last element of output:
 tensor([[ 0.6408, -0.7607, -0.2582,  0.0114,  0.2666,  0.6903,  0.0571, -0.7344,
          0.6606, -0.0910,  0.1453,  0.3249,  0.3311,  0.5930, -0.4965,  0.2050,
          0.7492, -0.3376, -0.6188,  0.6204,  0.3390,  0.3072, -0.4780, -0.5685,
         -0.2632, -0.2205,  0.6890, -0.0880,  0.0200,  0.3529, -0.3700,  0.4374,
         -0.0126,  0.1541,  0.3371, -0.0402, -0.1985,  0.4441, -0.6953,  0.1281,
          0.3387,  0.1841,  0.2238, -0.3183,  0.0580, -0.5339, -0.0698,  0.6681,
         -0.1433, -0.8731],
        [ 0.1879, -0.7572, -0.3976,  0.5002,  0.6435,  0.5008, -0.1933, -0.7205,
          0.7225, -0.0395, -0.1283, -0.3800, -0.3357,  0.2403, -0.4544, -0.2270,
          0.4730, -0.0095, -0.5744, -0.0314,  0.1183,  0.1553, -0.2954, -0.3117,
         -0.5891, -0.4046, -0.0498,  0.4663,  0.4232,  0.2188,  0.3219,  0.6677,
         -0.6420, -0.2342, -0.0232, -0.5081, -0.0918,  0.2458, -0.5321,  0.4054,
         -0.2385, -0.1152,  0.2350,  0.2997,  0.3205, -0

Then let us print out the last hidden state of last layer. 
Notice, we have two RNN layer, we only want to use the hidden state of last layer. 
You can find the these value are same as `output[-1]`.

In [45]:
print("last hidden state h_n:\n", hn[-1])

last hidden state h_n:
 tensor([[ 0.6408, -0.7607, -0.2582,  0.0114,  0.2666,  0.6903,  0.0571, -0.7344,
          0.6606, -0.0910,  0.1453,  0.3249,  0.3311,  0.5930, -0.4965,  0.2050,
          0.7492, -0.3376, -0.6188,  0.6204,  0.3390,  0.3072, -0.4780, -0.5685,
         -0.2632, -0.2205,  0.6890, -0.0880,  0.0200,  0.3529, -0.3700,  0.4374,
         -0.0126,  0.1541,  0.3371, -0.0402, -0.1985,  0.4441, -0.6953,  0.1281,
          0.3387,  0.1841,  0.2238, -0.3183,  0.0580, -0.5339, -0.0698,  0.6681,
         -0.1433, -0.8731],
        [ 0.1879, -0.7572, -0.3976,  0.5002,  0.6435,  0.5008, -0.1933, -0.7205,
          0.7225, -0.0395, -0.1283, -0.3800, -0.3357,  0.2403, -0.4544, -0.2270,
          0.4730, -0.0095, -0.5744, -0.0314,  0.1183,  0.1553, -0.2954, -0.3117,
         -0.5891, -0.4046, -0.0498,  0.4663,  0.4232,  0.2188,  0.3219,  0.6677,
         -0.6420, -0.2342, -0.0232, -0.5081, -0.0918,  0.2458, -0.5321,  0.4054,
         -0.2385, -0.1152,  0.2350,  0.2997,  0.3205, -0.

Let us compute the final tweet representation:

In [46]:
tweet_output_embeddings = output[-1,:,:] # -1 fetches the embeddings from the last timestep
print("tweet output embeddings size: ", tweet_output_embeddings.size())
# first dimension - number of tweets in the batch (4)
# second dimension - number of features in hidden state h_t (50, size of the hidden layer)

tweet output embeddings size:  torch.Size([4, 50])


In [47]:
tweet_output_embeddings

tensor([[ 0.6408, -0.7607, -0.2582,  0.0114,  0.2666,  0.6903,  0.0571, -0.7344,
          0.6606, -0.0910,  0.1453,  0.3249,  0.3311,  0.5930, -0.4965,  0.2050,
          0.7492, -0.3376, -0.6188,  0.6204,  0.3390,  0.3072, -0.4780, -0.5685,
         -0.2632, -0.2205,  0.6890, -0.0880,  0.0200,  0.3529, -0.3700,  0.4374,
         -0.0126,  0.1541,  0.3371, -0.0402, -0.1985,  0.4441, -0.6953,  0.1281,
          0.3387,  0.1841,  0.2238, -0.3183,  0.0580, -0.5339, -0.0698,  0.6681,
         -0.1433, -0.8731],
        [ 0.1879, -0.7572, -0.3976,  0.5002,  0.6435,  0.5008, -0.1933, -0.7205,
          0.7225, -0.0395, -0.1283, -0.3800, -0.3357,  0.2403, -0.4544, -0.2270,
          0.4730, -0.0095, -0.5744, -0.0314,  0.1183,  0.1553, -0.2954, -0.3117,
         -0.5891, -0.4046, -0.0498,  0.4663,  0.4232,  0.2188,  0.3219,  0.6677,
         -0.6420, -0.2342, -0.0232, -0.5081, -0.0918,  0.2458, -0.5321,  0.4054,
         -0.2385, -0.1152,  0.2350,  0.2997,  0.3205, -0.5896,  0.3140,  0.0941,


## RNN for Sentiment Analysis

In this section we will implement RNN for classifying the sentiment of the tweet (same task used in our previous feedforward neural networks tutorial).

We will pick up most of the functions from our feedforward neural networks code:

In [48]:
# all the necessary imports
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torch import optim

# set the seed (for reproducibility)
manual_seed = 123
torch.manual_seed(manual_seed)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
n_gpu = torch.cuda.device_count()
if n_gpu > 0:
  torch.cuda.manual_seed(manual_seed)

# hyperparameters
MAX_EPOCHS = 5 # number of passes over the training data
LEARNING_RATE = 0.3 # learning rate for the weight update rule
NUM_CLASSES = 3 # number of classes for the problem
EMBEDDING_SIZE = 300 # size of the word embedding

Now we can define the full RNN model:

In [49]:
"""
create a model for RNN
"""
class RNNmodel(nn.Module):
  
  def __init__(self, embedding_size, vocab_size, output_size, hidden_size, num_layers):
    # In the constructor we define the layers for our model
    super(RNNmodel, self).__init__()
    # word embedding lookup table
    self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_size, sparse=True)
    # core RNN module
    self.rnn_layer = nn.RNN(input_size=embedding_size, hidden_size=hidden_size, num_layers=num_layers) 
    # activation function
    self.activation_fn = nn.ReLU()
    # classification related modules
    self.linear_layer = nn.Linear(hidden_size, output_size) 
    self.softmax_layer = nn.LogSoftmax(dim=0)
    self.debug = False
  
  def forward(self, x):
    # In the forward function we define the forward propagation logic
    if self.debug:
        print("input word indices shape = ", x.size())
    out = self.embedding(x)
    if self.debug:
        print("word embeddings shape = ", out.size())
    out, _ = self.rnn_layer(out) # since we are not feeding h_0 explicitly, h_0 will be initialized to zeros by default
    if self.debug:
        print("RNN output (features from last layer of RNN for all timesteps) shape = ", out.size())
    # classify based on the hidden representation after RNN processes the last token
    out = out[-1]
    if self.debug:
        print("Tweet embeddings or RNN output (features from last layer of RNN for the last timestep only) shape = ", out.size())
    out = self.activation_fn(out)
    if self.debug:
        print("ReLU output shape = ", out.size())
    out = self.linear_layer(out)
    if self.debug:
        print("linear layer output shape = ", out.size())
    out = self.softmax_layer(out) # accepts 2D or more dimensional inputs
    if self.debug:
        print("softmax layer output shape = ", out.size())
    return out

Some additional hyperparameters for RNN

In [50]:
# hyperparameters of RNN
HIDDEN_SIZE = 50 # no. of units in the hidden layer
NUM_LAYERS = 2 # no. of hidden layers

Rest of the pipeline looks similar to our feedforward neural networks code (except that we are using **torchtext** instead of **DataLoader**):

In [51]:
from sklearn.metrics import accuracy_score

def train(loader):
    total_loss = 0.0
    # iterate throught the data loader
    num_sample = 0
    for batch in loader:
        # load the current batch
        batch_input = batch.tweet
        batch_output = batch.label
        
        batch_input = batch_input.to(device)
        batch_output = batch_output.to(device)
        # forward propagation
        # pass the data through the model
        model_outputs = model(batch_input)
        # compute the loss
        cur_loss = criterion(model_outputs, batch_output)
        total_loss += cur_loss.item()

        # backward propagation (compute the gradients and update the model)
        # clear the buffer
        optimizer.zero_grad()
        # compute the gradients
        cur_loss.backward()
        # update the weights
        optimizer.step()

        num_sample += batch_output.shape[0]
    return total_loss/num_sample

# evaluation logic based on classification accuracy
def evaluate(loader):
    all_pred=[]
    all_label = []
    with torch.no_grad(): # impacts the autograd engine and deactivate it. reduces memory usage and speeds up computation
        for batch in loader:
             # load the current batch
            batch_input = batch.tweet
            batch_output = batch.label

            batch_input = batch_input.to(device)
            # forward propagation
            # pass the data through the model
            model_outputs = model(batch_input)
            # identify the predicted class for each example in the batch
            probabilities, predicted = torch.max(model_outputs.cpu().data, 1)
            # put all the true labels and predictions to two lists
            all_pred.extend(predicted)
            all_label.extend(batch_output)
            
    accuracy = accuracy_score(all_label, all_pred)
    return accuracy

Let us define the RNN model.

In [52]:
# define the model
model = RNNmodel(EMBEDDING_SIZE, VOCAB_SIZE, NUM_CLASSES, HIDDEN_SIZE, NUM_LAYERS) 
model.to(device) # ship it to the right device

# define the loss function (last node of the graph)
criterion = nn.NLLLoss()

Let us make a full forward propagation pass over a sample input batch to the RNN model. Closely pay attention to the shapes of intermediate layers (by turning on debug mode of the model)

In [53]:
# turn on the debug mode
model.debug = True

# print the sample input batch and labels
print("sample input = ", tweets)
print("sample output = ", labels)

# feed the batch as input to the RNN model
model_prediction = model(tweets)
print('model prediction shape = ', model_prediction.size())

# feed the model prediction and labels to the loss function
loss = criterion(model_prediction, labels)
print("loss = ", loss.item())

# turn off the debug mode (as we go for training from now)
model.debug = False

sample input =  tensor([[ 191,    4, 1273,   49],
        [  14,   82,    2,    0],
        [   2,   73,  215,   18],
        [ 598,  145,   48,  215],
        [  21,   21,   21,   21]])
sample output =  tensor([0, 1, 0, 0])
input word indices shape =  torch.Size([5, 4])
word embeddings shape =  torch.Size([5, 4, 300])
RNN output (features from last layer of RNN for all timesteps) shape =  torch.Size([5, 4, 50])
Tweet embeddings or RNN output (features from last layer of RNN for the last timestep only) shape =  torch.Size([4, 50])
ReLU output shape =  torch.Size([4, 50])
linear layer output shape =  torch.Size([4, 3])
softmax layer output shape =  torch.Size([4, 3])
model prediction shape =  torch.Size([4, 3])
loss =  1.3636480569839478


**We need to create a new directory 'ckpt/' to store our model checkpoint.**

In [55]:
import os
if not os.path.exists("./ckpt"): # check if the directory doesn't exist already
    os.mkdir("./ckpt")

**Let us perform the training. We will save our model and optimizer at end of each epoch.**


You can find more information of saving and loading model [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

In [56]:
# create an instance of SGD with required hyperparameters
optimizer = torch.optim.SGD(model.parameters(), lr=LEARNING_RATE)

# start the training
for epoch in range(MAX_EPOCHS):
    # train the model for one pass over the data
    train_loss = train(train_iter)  
    # compute the training accuracy
    train_acc = evaluate(train_iter)
    # compute the validation accuracy
    val_acc = evaluate(val_iter)
    
    # print the loss for every epoch
    print('Epoch [{}/{}], Loss: {:.4f}, Training Accuracy: {:.4f}, Validation Accuracy: {:.4f}'.format(epoch+1, MAX_EPOCHS, train_loss, train_acc, val_acc))
    
    # save model, optimizer, and number of epoch to a dictionary
    model_save = {
            'epoch': epoch,  # number of epoch
            'model_state_dict': model.state_dict(), # model parameters 
            'optimizer_state_dict': optimizer.state_dict(), # save optimizer 
            'loss': train_loss # training loss
            }
    
    # use torch.save to store 
    torch.save(model_save, "./ckpt/model_{}.pt".format(epoch))

Epoch [1/5], Loss: 0.3479, Training Accuracy: 0.3750, Validation Accuracy: 0.3667
Epoch [2/5], Loss: 0.3464, Training Accuracy: 0.3947, Validation Accuracy: 0.3572
Epoch [3/5], Loss: 0.3460, Training Accuracy: 0.3920, Validation Accuracy: 0.3342
Epoch [4/5], Loss: 0.3459, Training Accuracy: 0.4335, Validation Accuracy: 0.3707
Epoch [5/5], Loss: 0.3421, Training Accuracy: 0.4560, Validation Accuracy: 0.3747


We trained the network only for 5 epochs, but it already overfits on validation set after epoch 2. 
In the coming sessions, we will look at methods to ``regularize`` the network (this will help us deal with overfitting).

**Load model checkpoint** 

When we have a trained model checkpint, we can load it using `torch.load()`

In [57]:
# define a new model
model2 = RNNmodel(EMBEDDING_SIZE, VOCAB_SIZE, NUM_CLASSES, HIDDEN_SIZE, NUM_LAYERS) 

# load checkpoint 
checkpoint = torch.load("./ckpt/model_1.pt") # loading the model obatined after 2nd epoch

# assign the parameters of checkpoint to this new model
model2.load_state_dict(checkpoint['model_state_dict'])
model2.to(device)

print(model2) # can be used for inference or for further training

RNNmodel(
  (embedding): Embedding(3340, 300, sparse=True)
  (rnn_layer): RNN(300, 50, num_layers=2)
  (activation_fn): ReLU()
  (linear_layer): Linear(in_features=50, out_features=3, bias=True)
  (softmax_layer): LogSoftmax()
)


## GRUs

Gated Recurrent Units (GRUs) are a variant of RNNs that use more complex units for activation. They are created to have more persistent memory thereby making them easier for RNNs to capture long-term dependencies. To learn the theory behind GRUs, we recommend: https://github.com/UBC-NLP/dlnlp2019/blob/master/slides/RNN.pdf 

GRU is defined by ``torch.nn.GRU`` module and its documentation can be fetched [here](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html#gru). Now let us define the GRU module.

In [58]:
"""
define the GRU module
"""
# first input - number of word vector dimensions/embeddings
# second input - number of nodes in hidden layer (50, size of the hidden layer)
# third input - number of recurrent layers (2)
gru_rnn = nn.GRU(input_size=300, hidden_size=50, num_layers=2) # input_size, hidden_size, num_layers

Similar to RNN, GRU module takes two inputs: *the initial hidden state for each element in the batch* (t=0) and the *input features* (``tweet_input_embeddings`` in our case).

Let us feed both the initial hidden state and tweet embeddings to our GRU model.

In [59]:
"""
forward propagation over the GRU model
"""
output, hn = gru_rnn(tweet_input_embeddings, h0) # h0 is optional input, defaults to tensor of 0's when not provided

``output`` tensor contains the output features $h_t$ from the last layer of the GRU

In [60]:
# output = seq_len, batch, hidden_size (output features from last layer of GRU)
print("output size: ", output.size())

output size:  torch.Size([5, 4, 50])


``hn`` is a tensor of shape (num_layers, batch_size, hidden_size / number of nodes in a hidden layer) containing the hidden state for last time step ``t = max_seq_len`` for the ``2 layered RNN``.

In [61]:
# h_n = num_layers, batch, hidden_size (hidden state for t=seq_len or hidden state at last timestep)
print("last hidden state size: ", hn.size())

last hidden state size:  torch.Size([2, 4, 50])


Similar to RNN, you can compute the final tweet representation (representation from last hidden state for each tweet) as follows.

In [62]:
tweet_output_embeddings = output[-1,:,:] # -1 fetches the embeddings from the last timestep
print("tweet output embeddings size: ", tweet_output_embeddings.size())
# first dimension - number of tweets in the batch (5)
# second dimension - number of features in hidden state h_t (20, size of the hidden layer)

tweet output embeddings size:  torch.Size([4, 50])


## LSTMs

Long short-term memory (LSTMs) are a variant of RNNs that use more complex units for activation. Similar to the spirit of GRU, they are created to have more persistent memory thereby making them easier for RNNs to capture long-term dependencies. To learn the theory behind GRUs, we recommend: https://github.com/UBC-NLP/dlnlp2019/blob/master/slides/RNN.pdf 

LSTM is defined by ``torch.nn.LSTM`` module and its documentation can be fetched [here](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html#lstm). Now let us define the LSTM module.

In [63]:
"""
define the LSTM module
"""
# first input - number of features in x (300, size of the word embedding)
# second input - number of number of nodes in a hidden layer (50)
# third input - number of recurrent layers (2)
lstm_rnn = nn.LSTM(input_size=300, hidden_size=50, num_layers=2) # input_size, hidden_size, num_layers

Unlike RNN and GRU, LSTM module takes **three inputs**: the **initial hidden state** for each element in the batch (t=0), the **input features** (tweet_input_embeddings in our case) and the **initial cell state** for each element in the batch.

Let us construct the initial cell state (this construction is similar to that of initial hidden state)

In [64]:
"""
cell state at time-step 0 (h_0)
"""
# first dimension - number of LSTM layers (2)
# second dimension - batch_size (# of tweets/examples/sentences)
# third dimension - hidden_size / number of nodes in a hidden layer (50)
c0 = torch.randn(2, 4, 50)

Let us feed the initial hidden state, initial cell state and tweet embeddings to our LSTM model.

In [65]:
"""
forward propagation over the LSTM model
"""
output, (hn, cn) = lstm_rnn(tweet_input_embeddings, (h0, c0)) # h0 and c0 is optional input, defaults to tensor of 0's when not provided

``output`` tensor contains the output features $h_t$ from the last layer of the LSTM

In [66]:
# output = seq_len, batch_size, hidden_size (output features from last layer of LSTM)
print("output size: ", output.size())

output size:  torch.Size([5, 4, 50])


``hn`` is a tensor of shape (num_layers, batch, hidden_size) containing the hidden state for t = seq_len

In [67]:
# h_n = num_layers, batch, hidden_size (hidden state for t=seq_len or hidden state at last timestep)
print("last hidden state size: ", hn.size())

last hidden state size:  torch.Size([2, 4, 50])


``cn`` is a tensor of shape (num_layers, batch, hidden_size) containing the cell state for t = seq_len.

In [68]:
# c_n = num_layers, batch_size, hidden_size (cell state for t=seq_len or cell state at last timestep)
print("last cell state size: ", hn.size())

last cell state size:  torch.Size([2, 4, 50])


Similar to RNN and GRU, you can compute the final tweet representation (representation from last hidden state for each tweet) as follows.

In [69]:
tweet_output_embeddings = output[-1,:,:] # -1 fetches the embeddings from the last timestep
print("tweet output embeddings size: ", tweet_output_embeddings.size())
# first dimension - number of tweets in the batch (4)
# second dimension - number of features in hidden state h_t (50, size of the hidden layer)

tweet output embeddings size:  torch.Size([4, 50])


That's it!